# Виправлена конфігурація з правильним доступом до тем
services:
   # База даних MySQL
   mysql:
      image: mysql:8.0
      restart: always
      ports:
         - '3307:3306'
      volumes:
         - './.data/mysql:/var/lib/mysql'
      environment:
         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
         MYSQL_DATABASE: ${MYSQL_DATABASE}
         MYSQL_USER: ${MYSQL_USER}
         MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      networks:
         - wp-network
      command: --default-authentication-plugin=mysql_native_password
      healthcheck:
         test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
         interval: 30s
         timeout: 10s
         retries: 3

   # WordPress з PHP-FPM
   wordpress:
      image: wordpress:fpm-alpine
      depends_on:
         mysql:
            condition: service_healthy
         redis:
            condition: service_healthy
      restart: always
      environment:
         WORDPRESS_DB_HOST: mysql:3306
         WORDPRESS_DB_USER: ${MYSQL_USER}
         WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
         WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
         WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
         WORDPRESS_CONFIG_EXTRA: |
            define('WP_MEMORY_LIMIT', '256M');
            define('WP_REDIS_HOST', 'redis');
            define('WP_REDIS_PORT', 6379);
            define('WP_REDIS_DATABASE', 0);
            define('WP_CACHE', true);
            define('WP_REDIS_PREFIX', '${WORDPRESS_TABLE_PREFIX}');
         WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      volumes:
         - './.data/wordpress:/var/www/html'
         - './wp-content:/var/www/html/wp-content'
      networks:
         - wp-network

   # Caddy веб-сервер з автоматичним SSL
   caddy:
      image: caddy:alpine
      depends_on:
         - wordpress
      ports:
         - '80:80'
         - '443:443'
      volumes:
         - './.data/wordpress:/var/www/html'
         - './wp-content:/var/www/html/wp-content'
         - './Caddyfile:/etc/caddy/Caddyfile'
         - './.data/caddy:/data'
         - './.data/caddy-config:/config'
      networks:
         - wp-network
      restart: always

   # Redis для кешування
   redis:
      image: redis:alpine
      restart: always
      volumes:
         - './.data/redis:/data'
      networks:
         - wp-network
      healthcheck:
         test: ['CMD', 'redis-cli', 'ping']
         interval: 30s
         timeout: 10s
         retries: 3

   # Adminer для управління БД
   adminer:
      image: adminer:latest
      depends_on:
         mysql:
            condition: service_healthy
      restart: always
      environment:
         ADMINER_DEFAULT_SERVER: mysql
         ADMINER_DESIGN: dracula
      ports:
         - '8080:8080'
      networks:
         - wp-network

   # MailHog для тестування електронної пошти
   mailhog:
      image: mailhog/mailhog
      restart: always
      ports:
         - '1025:1025'  # SMTP порт
         - '8025:8025'  # Веб-інтерфейс
      networks:
         - wp-network

# Мережа
networks:
   wp-network:
      driver: bridge